// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKEnwUIO39IL59fK9ppfn5pm6_8nPV9nE',
    appId: '1:245154033762:web:5eac1d57d1c22fc188e13b',
    messagingSenderId: '245154033762',
    projectId: 'course-advisory',
    authDomain: 'course-advisory.firebaseapp.com',
    storageBucket: 'course-advisory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmkWkmRFTxBR6uFQPW3BvC8nE3nL1xlY',
    appId: '1:245154033762:android:6fa717e2a00121a988e13b',
    messagingSenderId: '245154033762',
    projectId: 'course-advisory',
    storageBucket: 'course-advisory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_sFTvkfJHAk8iCWV8UWLCeiWezjWY8Ic',
    appId: '1:245154033762:ios:8f9768954eafe41d88e13b',
    messagingSenderId: '245154033762',
    projectId: 'course-advisory',
    storageBucket: 'course-advisory.appspot.com',
    iosClientId: '245154033762-obn1n4ukhaok7dqkcc4u0q20ug8kjvtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_sFTvkfJHAk8iCWV8UWLCeiWezjWY8Ic',
    appId: '1:245154033762:ios:8f9768954eafe41d88e13b',
    messagingSenderId: '245154033762',
    projectId: 'course-advisory',
    storageBucket: 'course-advisory.appspot.com',
    iosClientId: '245154033762-obn1n4ukhaok7dqkcc4u0q20ug8kjvtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
